# Generated by Django 5.2.4 on 2026-05-28 13:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                (
                    "general_info",
                    models.TextField(blank=True, max_length=50000, null=True),
                ),
                (
                    "filter_info",
                    models.TextField(blank=True, max_length=50000, null=True),
                ),
                (
                    "analysis_features",
                    models.TextField(blank=True, max_length=50000, null=True),
                ),
                (
                    "report_info",
                    models.TextField(blank=True, max_length=50000, null=True),
                ),
                (
                    "report_text",
                    models.TextField(blank=True, max_length=50000, null=True),
                ),
                (
                    "report_tech",
                    models.TextField(blank=True, max_length=50000, null=True),
                ),
            ],
            options={
                "db_table": "disease",
            },
        ),
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "gene",
            },
        ),
        migrations.CreateModel(
            name="HistoricalGene",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical gene",
                "verbose_name_plural": "historical genes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("genes", models.ManyToManyField(blank=True, null=True, to="api.gene")),
            ],
            options={
                "db_table": "panel",
            },
        ),
        migrations.CreateModel(
            name="DiseasePanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.disease"
                    ),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.panel"
                    ),
                ),
            ],
            options={
                "db_table": "disease_panel",
            },
        ),
        migrations.AddField(
            model_name="disease",
            name="associated_panels",
            field=models.ManyToManyField(
                blank=True, null=True, through="api.DiseasePanel", to="api.panel"
            ),
        ),
        migrations.AddConstraint(
            model_name="diseasepanel",
            constraint=models.UniqueConstraint(
                fields=("disease", "panel"), name="unique_disease_panel"
            ),
        ),
    ]
