# Generated by Django 5.2.8 on 2025-12-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('comment', models.TextField(max_length=50000, null=True)),
                ('analysis_comment', models.TextField(max_length=50000, null=True)),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('genes', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'panel',
            },
        ),
        migrations.CreateModel(
            name='DiseasePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disease')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.panel')),
            ],
            options={
                'db_table': 'disease_panel',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='associated_panels',
            field=models.ManyToManyField(blank=True, through='api.DiseasePanel', to='api.panel'),
        ),
    ]
