# Generated by Django 5.2.4 on 2026-01-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panel",
            name="name",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
