# Generated by Django 5.2.4 on 2025-12-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="diseasepanel",
            constraint=models.UniqueConstraint(
                fields=("disease", "panel"), name="unique_disease_panel"
            ),
        ),
    ]
