# Generated by Django 5.2.4 on 2025-08-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="associated_panels",
            field=models.ManyToManyField(blank=True, to="api.panel"),
        ),
    ]
