# Generated by Django 5.2.4 on 2025-12-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_diseasepanel_unique_disease_panel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="analysis_comment",
            field=models.TextField(max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="comment",
            field=models.TextField(max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name="disease",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_disease_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="panel",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_panel_name"
            ),
        ),
    ]
