# Generated by Django 5.2.4 on 2026-01-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_panel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene",
            name="symbol",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
