# Generated by Django 5.2.4 on 2025-11-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_disease_associated_panels"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="analysis_comment",
            field=models.TextField(max_length=50000, null=True),
        ),
    ]
