# Generated by Django 5.2.4 on 2026-05-28 14:28

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_historicaldisease_historicaldiseasepanel_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="historicalgene",
            table="gene_history",
        ),
        migrations.AlterModelTable(
            name="historicalpanel",
            table="panel_history",
        ),
        migrations.CreateModel(
            name="HistoricalPanel_genes",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gene",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.gene",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.historicalpanel",
                    ),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.panel",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalPanel_genes",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name="HistoricalDiseasePanel",
        ),
    ]
