# Generated by Django 5.2.4 on 2026-01-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_gene_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
