# Generated by Django 5.2.4 on 2026-06-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_historicalgene_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=50000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.disease"
                    ),
                ),
            ],
            options={
                "db_table": "editing_note",
            },
        ),
    ]
