# Generated by Django 5.2.4 on 2025-12-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_disease_analysis_comment_alter_disease_comment_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="disease",
            name="unique_disease_name",
        ),
        migrations.RemoveConstraint(
            model_name="panel",
            name="unique_panel_name",
        ),
        migrations.AlterField(
            model_name="disease",
            name="analysis_comment",
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="comment",
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
