# Generated by Django 5.2.4 on 2026-02-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_disease_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disease",
            name="analysis_comment",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="comment",
        ),
        migrations.AddField(
            model_name="disease",
            name="analysis_features",
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="analysis_notes",
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="report_info",
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="report_tech",
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="report_text",
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
