# Generated by Django 5.2.4 on 2026-02-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_disease_analysis_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="general_info",
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
