# Generated by Django 5.2.4 on 2026-02-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_disease_general_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="disease",
            old_name="analysis_notes",
            new_name="filter_info",
        ),
    ]
