# Generated by Django 5.2.8 on 2026-01-22 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('comment', models.TextField(blank=True, max_length=50000, null=True)),
                ('analysis_comment', models.TextField(blank=True, max_length=50000, null=True)),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'gene',
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('genes', models.ManyToManyField(blank=True, null=True, to='api.gene')),
            ],
            options={
                'db_table': 'panel',
            },
        ),
        migrations.CreateModel(
            name='DiseasePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disease')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.panel')),
            ],
            options={
                'db_table': 'disease_panel',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='associated_panels',
            field=models.ManyToManyField(blank=True, null=True, through='api.DiseasePanel', to='api.panel'),
        ),
        migrations.AddConstraint(
            model_name='diseasepanel',
            constraint=models.UniqueConstraint(fields=('disease', 'panel'), name='unique_disease_panel'),
        ),
    ]
